name: Scheduled repo analysis with git-sizer

on:
  schedule:
    - cron: '44 2 * * 0' # Runs on Sundays at 2:44 AM UTC; https://crontab.guru/#44_2_*_*_0
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run-git-sizer:
    name: git-sizer - ${{ github.repository }}
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Run git-sizer
        id: sizer
        uses: ChrisCarini/github-git-sizer-action@0a851f864e48e0a46c228a3626bb32eb21bb270a # v0.0.1
        with:
          flags: '--threshold=0'

      - name: Print git-sizer output
        run: |
          printf "%s\n" "${{ steps.sizer.outputs.result }}"
